language: ruby
rvm:
- 2.0.0
env:
  global:
  - secure: IpGM1CW5bsn8DGgcKGMf5jmlJMMVYVZ3c55d8MpGALgxbBHu2GLdOpA/msG1Ura1jR7sNZkrn1SlwQZ2Quo311RPb3UpgPQOlzphVPd6PzYbrNSccEeiD5cemm+J4zUUc6vSFLVwfDE4lV8Ge4Zbt+TclgBgJ4mw42/YB7N/Dmg=
  - secure: USgyoGyai6QdUMKjqO3UPIAFYT6Qy9GaL7dApTwSFWgS7hxYe+WnW5/NCP5YHoDzbKaMhBI7FUcLyROirNw5Ar2RxO/WS8YZ1msmmhgouV44fXcDz/K+oRX+8bKIP1p58T6lvkKtf/ywZ1wRLil0fxi6w7Xjnt2oYLRMzm0kt00=
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: deploygate
  on:
    tags: true
    repo: DeployGate/deploygate-cli
after_deploy:
- 'curl -X POST --data-urlencode "payload={\"text\": \"Released a deploygate gem in
  <https://rubygems.org/gems/deploygate/|RubyGems>\"}" $SLACK_URL'
