language: ruby
rvm:
- 2.0.0
env:
  global:
    secure: IpGM1CW5bsn8DGgcKGMf5jmlJMMVYVZ3c55d8MpGALgxbBHu2GLdOpA/msG1Ura1jR7sNZkrn1SlwQZ2Quo311RPb3UpgPQOlzphVPd6PzYbrNSccEeiD5cemm+J4zUUc6vSFLVwfDE4lV8Ge4Zbt+TclgBgJ4mw42/YB7N/Dmg=
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: GMEt+VCHGTvSIx/Z6iCTXE3eAbtNt6WB5Qr8AgMDOLjhuDcKCeGm6QEzcmBljnrtZmJhU1BIapzez5tS40H8wy/aRPknSsAOU+kt+BUIMfoQIv0KlVtWxI45R61+bytOfnrGqqLZKVC9mi/nI+qyHkLYuBa3FTEe9u4iyF8Ul/E=
  gem: deploygate
  on:
    tags: true
    repo: DeployGate/deploygate-cli
after_deploy:
- 'curl -X POST --data-urlencode "payload={\"text\": \"Released a deploygate gem in
  <https://rubygems.org/gems/deploygate/|RubyGems>\"}" $SLACK_URL'
