#!/bin/sh 
ORIG_DIR=$(pwd)
cd $(dirname "$0")
if [ -L "$(basename $0)" ] ; then
  cd $(dirname $(readlink $(basename "$0") ) )
fi
SCRIPT_DIR=$(pwd -P)
cd "$ORIG_DIR"
ruby -I $SCRIPT_DIR/lib $SCRIPT_DIR/dgate.rb "$@"
