name: Run jobs on every PR

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *" # everyday at 10am JST

jobs:
  build-ruby2:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6
          - 2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system 3.4.22 # The latest of Ruby 2.x support
      - run: bundle exec rake

  build-ruby3:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system
      - run: bundle exec rake

  instrument-ruby2:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.6
          - 2.7
    services:
      app:
        image: ghcr.io/deploygate/deploygate-mock-server:main
        ports:
          - 3000/tcp
        options: >-
          --health-cmd "curl -fI http://localhost:3000"
          --health-interval 15s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system 3.4.22 # The latest of Ruby 2.x support
      - run: |
          export HOME=${{ env.RUNNER_TEMP }}
          
          mkdir $HOME/.dg
          cat<<EOF > $HOME/.dg/credentials
          { "name": "owner_test_token", "token": "owner_test_token" }
          EOF
      - run: bundle exec dg deploy spec/fixtures/sample.apk
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}
      - run: bundle exec dg deploy spec/fixtures/sample.aab
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}
      - run: bundle exec dg deploy spec/fixtures/sample.ipa
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}

  instrument-ruby3:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    services:
      app:
        image: ghcr.io/deploygate/deploygate-mock-server:main
        ports:
          - 3000/tcp
        options: >-
          --health-cmd "curl -fI http://localhost:3000"
          --health-interval 15s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system
      - run: |
          export HOME=${{ env.RUNNER_TEMP }}
          
          mkdir $HOME/.dg
          cat<<EOF > $HOME/.dg/credentials
          { "name": "owner_test_token", "token": "owner_test_token" }
          EOF
      - run: bundle exec dg deploy spec/fixtures/sample.apk
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}
      - run: bundle exec dg deploy spec/fixtures/sample.aab
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}
      - run: bundle exec dg deploy spec/fixtures/sample.ipa
        env:
          DG_DEVELOP_URL: http://localhost:${{ job.services.app.ports[3000] }}
          HOME: ${{ env.RUNNER_TEMP }}
