name: Run jobs on every PR

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *" # everyday at 10am JST

jobs:
  build-ruby2:
    strategy:
      matrix:
        ruby_version:
          - 2.6
          - 2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system 3.4.22 # The latest of Ruby 2.x support
      - run: bundle exec rake

  build-ruby3:
    strategy:
      matrix:
        ruby_version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system
      - run: bundle exec rake

  instrument-ruby2:
    strategy:
      matrix:
        ruby_version:
          - 2.6
          - 2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system 3.4.22 # The latest of Ruby 2.x support
      - run: bundle exec rake

  instrument-ruby3:
    strategy:
      matrix:
        ruby_version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: gem update --system
      - run: bundle exec rake
